using System.Text.Json.Serialization;

namespace IconPackBuilder.Core.IconSources;

/// <summary>
/// Root of the <c>SeagullFluentIcons.json</c> asset that accompanies the Seagull font. Generated by the <c>IconPackBuilder.SeagullAssetsGenerator</c>
/// tool; not intended to be edited by hand.
/// </summary>
public sealed class SeagullIconsData
{
    public required string Version { get; init; }

    public required string FontFamilyName { get; init; }

    public required SeagullSourceInfo Source { get; init; }

    public required IReadOnlyList<string> Variants { get; init; }

    public required IReadOnlyList<SeagullIconData> Icons { get; init; }
}

/// <summary>
/// Describes where the font and metadata in a <see cref="SeagullIconsData"/> asset came from.
/// </summary>
public sealed class SeagullSourceInfo
{
    public required string FluentIconsCommonVersion { get; init; }

    public required string FluentIconsWinUIVersion { get; init; }

    public required string FluentIconsTag { get; init; }

    public required string UpstreamRepository { get; init; }

    public required string UpstreamCommit { get; init; }

    public required DateTime GeneratedUtc { get; init; }
}

/// <summary>
/// A single symbol in the Seagull font together with its Microsoft Fluent UI System Icons metadata (when a match was found).
/// </summary>
public sealed class SeagullIconData
{
    /// <summary>
    /// Gets the FluentIcons <c>Symbol</c> enum member name. Stable across versions and used as the icon group ID in projects.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Gets the FluentIcons <c>Symbol</c> enum value.
    /// </summary>
    public required int Value { get; init; }

    public required string Name { get; init; }

    public string? Description { get; init; }

    public IReadOnlyList<string> Metaphors { get; init; } = [];

    /// <summary>
    /// Gets the upstream <c>directionType</c> value (<c>mirror</c> or <c>unique</c>), if any.
    /// </summary>
    public string? DirectionType { get; init; }

    /// <summary>
    /// Gets the name of the upstream icon that the metadata was taken from, or <see langword="null"/> if no upstream icon matched.
    /// </summary>
    public string? UpstreamName { get; init; }

    /// <summary>
    /// Gets the glyphs present in the font for this symbol, keyed by variant name.
    /// </summary>
    public required IReadOnlyDictionary<string, SeagullGlyphData> Variants { get; init; }
}

/// <summary>
/// Code points for one variant of a symbol.
/// </summary>
public sealed class SeagullGlyphData
{
    public required int CodePoint { get; init; }

    /// <summary>
    /// Gets the code point of the right-to-left glyph, or <see langword="null"/> if the RTL glyph is identical to the LTR glyph.
    /// </summary>
    public int? RtlCodePoint { get; init; }
}

[JsonSourceGenerationOptions(
    WriteIndented = true,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(SeagullIconsData))]
public sealed partial class SeagullIconsJsonContext : JsonSerializerContext;
