using System.Text;
using IconPackBuilder.Data;
using Singulink.IO;

namespace IconPackBuilder.Core.Services;

/// <summary>
/// Writes a static C# class with an <c>IconGlyph</c> / <c>IconWithRtlGlyph</c> member per icon for use with the Singulink.UI.Icons packages.
/// </summary>
public sealed class CSharpExporter : IExporter
{
    public static CSharpExporter Instance { get; } = new();

    public string Name => "C# Exporter";

    public ExportFormat Format => ExportFormat.CSharp;

    public async Task SaveAsync(ExportContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Icon Pack Builder");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using Singulink.UI.Icons;");
        sb.AppendLine();
        sb.AppendLine(null, $"namespace {context.NamespaceName};");
        sb.AppendLine();
        sb.AppendLine(null, $"public static class {context.ClassName}");
        sb.AppendLine("{");

        foreach (var (memberName, icon) in context.GetMembers())
        {
            string codePointLiteral = FormatCodePoint(icon.Icon.CodePoint);

            if (icon.Icon.RtlCodePoint is int rtlCodePoint)
            {
                string rtlCodePointLiteral = FormatCodePoint(rtlCodePoint);
                sb.AppendLine(null, $"    public static IconWithRtlGlyph {memberName} {{ get; }} = new({codePointLiteral}, {rtlCodePointLiteral});");
            }
            else
            {
                sb.AppendLine(null, $"    public static IconGlyph {memberName} {{ get; }} = new({codePointLiteral});");
            }
        }

        sb.AppendLine("}");

        var file = context.ExportDir.CombineFile(context.ClassName + ".cs", PathOptions.None);
        await File.WriteAllTextAsync(file.PathExport, sb.ToString());
    }

    private static string FormatCodePoint(int codePoint) => $"0x{codePoint:X4}";
}
