using System.Text;
using Singulink.IO;

namespace IconPackBuilder.Core.Services;

public class CSharpExporter : IExporter
{
    public static CSharpExporter Instance { get; } = new();

    public string Name => "C# Exporter";

    public async Task SaveAsync(string projectName, IAbsoluteDirectoryPath exportDir, IEnumerable<ExportIconInfo> icons, string defaultVariantName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(projectName);

        var (namespaceName, className) = ParseProjectName(projectName);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Icon Pack Builder");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using Singulink.UI.Icons;");
        sb.AppendLine();
        sb.AppendLine(null, $"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine(null, $"public static class {className}");
        sb.AppendLine("{");

        var memberNames = new HashSet<string>();

        foreach (var icon in icons.OrderBy(i => i.ExportName).ThenBy(i => i.Icon.Variant, StringComparer.Ordinal))
        {
            string memberName = GetMemberName(icon.ExportName, icon.Icon.Variant, defaultVariantName);
            string codePointLiteral = FormatCodePoint(icon.Icon.CodePoint);

            if (!memberNames.Add(memberName))
                throw new InvalidOperationException($"Duplicate icon member name detected: {memberName}");

            if (icon.Icon.RtlCodePoint is int rtlCodePoint)
            {
                string rtlCodePointLiteral = FormatCodePoint(rtlCodePoint);
                sb.AppendLine(null, $"    public static readonly IconWithRtlGlyph {memberName} = new({codePointLiteral}, {rtlCodePointLiteral});");
            }
            else
            {
                sb.AppendLine(null, $"    public static readonly IconGlyph {memberName} = new({codePointLiteral});");
            }
        }

        sb.AppendLine("}");

        var file = exportDir.CombineFile(className + ".cs", PathOptions.None);
        await File.WriteAllTextAsync(file.PathExport, sb.ToString());
    }

    private static (string Namespace, string ClassName) ParseProjectName(string projectName)
    {
        int lastDotIndex = projectName.LastIndexOf('.');

        if (lastDotIndex < 0)
            return (projectName, projectName);

        return (projectName[..lastDotIndex], projectName[(lastDotIndex + 1)..]);
    }

    private static string GetMemberName(string exportName, string variant, string defaultVariantName)
    {
        return variant == defaultVariantName ? exportName : exportName + variant;
    }

    private static string FormatCodePoint(int codePoint) => $"0x{codePoint:X4}";
}
