using System.Text;
using IconPackBuilder.Data;
using Singulink.IO;

namespace IconPackBuilder.Core.Services;

/// <summary>
/// Writes a stylesheet with an <c>@font-face</c> rule for the subset font, a base class that applies the font, and a class per icon that
/// renders its glyph in a <c>::before</c> pseudo-element. Icons with a distinct right-to-left glyph get a second rule that applies it when
/// the element's directionality is right-to-left.
/// </summary>
public sealed class CssExporter : IExporter
{
    public static CssExporter Instance { get; } = new();

    public string Name => "CSS Exporter";

    public ExportFormat Format => ExportFormat.Css;

    /// <summary>
    /// Gets the CSS class prefix for a project: the kebab-cased class name, e.g. <c>font-icons</c> for <c>MyApp.FontIcons</c>.
    /// </summary>
    public static string GetClassPrefix(ExportContext context) => ExportContext.ToKebabCase(context.ClassName);

    /// <summary>
    /// Gets the CSS class name of an icon member, e.g. <c>font-icons-save-filled</c> for <c>SaveFilled</c>.
    /// </summary>
    public static string GetIconClassName(ExportContext context, string memberName) => GetClassPrefix(context) + "-" + ExportContext.ToKebabCase(memberName);

    public async Task SaveAsync(ExportContext context)
    {
        string prefix = GetClassPrefix(context);
        string fontFormat = GetFontFormat(context.FontFileName);
        var members = context.GetMembers();

        var sb = new StringBuilder();
        sb.AppendLine("/* Generated by Icon Pack Builder */");
        sb.AppendLine();
        sb.AppendLine(null, $"/* Usage: <i class=\"{prefix} {prefix}-{(members.Count > 0 ? ExportContext.ToKebabCase(members[0].Name) : "icon-name")}\" aria-hidden=\"true\"></i> */");
        sb.AppendLine();
        sb.AppendLine("@font-face {");
        sb.AppendLine(null, $"    font-family: \"{context.ProjectName}\";");
        sb.AppendLine(null, $"    src: url(\"{context.FontFileName}\") format(\"{fontFormat}\");");
        sb.AppendLine("    font-weight: normal;");
        sb.AppendLine("    font-style: normal;");
        sb.AppendLine("    font-display: block;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(null, $".{prefix} {{");
        sb.AppendLine(null, $"    font-family: \"{context.ProjectName}\";");
        sb.AppendLine("    font-weight: normal;");
        sb.AppendLine("    font-style: normal;");
        sb.AppendLine("    font-variant: normal;");
        sb.AppendLine("    line-height: 1;");
        sb.AppendLine("    text-transform: none;");
        sb.AppendLine("    letter-spacing: normal;");
        sb.AppendLine("    display: inline-block;");
        sb.AppendLine("    speak: never;");
        sb.AppendLine("    -webkit-font-smoothing: antialiased;");
        sb.AppendLine("    -moz-osx-font-smoothing: grayscale;");
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var (memberName, icon) in members)
        {
            string className = GetIconClassName(context, memberName);
            sb.AppendLine(null, $".{className}::before {{ content: \"{FormatCodePoint(icon.Icon.CodePoint)}\"; }}");

            // :dir() matches the element's directionality (from a dir attribute on it or an ancestor), which is how documents opt into
            // right-to-left layouts.
            if (icon.Icon.RtlCodePoint is int rtlCodePoint)
                sb.AppendLine(null, $".{className}:dir(rtl)::before {{ content: \"{FormatCodePoint(rtlCodePoint)}\"; }}");
        }

        var file = context.ExportDir.CombineFile(context.ClassName + ".css", PathOptions.None);
        await File.WriteAllTextAsync(file.PathExport, sb.ToString());
    }

    private static string GetFontFormat(string fontFileName) => Path.GetExtension(fontFileName).ToLowerInvariant() switch {
        ".otf" => "opentype",
        ".ttf" => "truetype",
        ".woff" => "woff",
        ".woff2" => "woff2",
        var ext => throw new InvalidOperationException($"Unsupported font file extension '{ext}'."),
    };

    private static string FormatCodePoint(int codePoint) => $"\\{codePoint:X}";
}
