using System.Text;
using IconPackBuilder.Data;
using Singulink.IO;

namespace IconPackBuilder.Core.Services;

/// <summary>
/// Writes an ES module with an object per icon (its CSS class name from the stylesheet export and its glyphs) plus a TypeScript declaration
/// file, so the icons can be used by name from plain JavaScript and from TypeScript without a build step.
/// </summary>
public sealed class JavaScriptExporter : IExporter
{
    public static JavaScriptExporter Instance { get; } = new();

    public string Name => "JavaScript Exporter";

    public ExportFormat Format => ExportFormat.JavaScript;

    public async Task SaveAsync(ExportContext context)
    {
        var members = context.GetMembers();
        string className = context.ClassName;

        var js = new StringBuilder();
        js.AppendLine("// Generated by Icon Pack Builder");
        js.AppendLine();
        js.AppendLine("/**");
        js.AppendLine(null, $" * Icons in the {context.ProjectName} pack. `className` is the icon's class in {className}.css; `glyph` and `rtlGlyph` are the");
        js.AppendLine(null, $" * characters to render with the \"{context.ProjectName}\" font directly (they are equal for icons without a mirrored version).");
        js.AppendLine(" */");
        js.AppendLine(null, $"export const {className} = Object.freeze({{");

        foreach (var (memberName, icon) in members)
        {
            string glyph = FormatGlyph(icon.Icon.CodePoint);
            string rtlGlyph = FormatGlyph(icon.Icon.RtlCodePoint ?? icon.Icon.CodePoint);
            js.AppendLine(null, $"    {memberName}: Object.freeze({{ className: \"{CssExporter.GetIconClassName(context, memberName)}\", glyph: \"{glyph}\", rtlGlyph: \"{rtlGlyph}\" }}),");
        }

        js.AppendLine("});");
        js.AppendLine();
        js.AppendLine("/**");
        js.AppendLine(" * Returns the glyph to render for an icon, using its right-to-left version when `rtl` is true.");
        js.AppendLine(" * @param {{ glyph: string, rtlGlyph: string }} icon");
        js.AppendLine(" * @param {boolean} [rtl]");
        js.AppendLine(" * @returns {string}");
        js.AppendLine(" */");
        js.AppendLine("export function getGlyph(icon, rtl = false) {");
        js.AppendLine("    return rtl ? icon.rtlGlyph : icon.glyph;");
        js.AppendLine("}");

        var dts = new StringBuilder();
        dts.AppendLine("// Generated by Icon Pack Builder");
        dts.AppendLine();
        dts.AppendLine("/** An icon in the pack: its CSS class name and the characters to render with the icon font. */");
        dts.AppendLine("export interface IconGlyph {");
        dts.AppendLine("    /** The icon's CSS class name in the exported stylesheet. */");
        dts.AppendLine("    readonly className: string;");
        dts.AppendLine("    /** The character to render with the icon font. */");
        dts.AppendLine("    readonly glyph: string;");
        dts.AppendLine("    /** The character to render in right-to-left layouts; equal to `glyph` for icons without a mirrored version. */");
        dts.AppendLine("    readonly rtlGlyph: string;");
        dts.AppendLine("}");
        dts.AppendLine();
        dts.AppendLine(null, $"/** Icons in the {context.ProjectName} pack. */");
        dts.AppendLine(null, $"export declare const {className}: {{");

        foreach (var (memberName, _) in members)
            dts.AppendLine(null, $"    readonly {memberName}: IconGlyph;");

        dts.AppendLine("};");
        dts.AppendLine();
        dts.AppendLine("/** Returns the glyph to render for an icon, using its right-to-left version when `rtl` is true. */");
        dts.AppendLine("export declare function getGlyph(icon: IconGlyph, rtl?: boolean): string;");

        var jsFile = context.ExportDir.CombineFile(className + ".js", PathOptions.None);
        var dtsFile = context.ExportDir.CombineFile(className + ".d.ts", PathOptions.None);

        await File.WriteAllTextAsync(jsFile.PathExport, js.ToString());
        await File.WriteAllTextAsync(dtsFile.PathExport, dts.ToString());
    }

    private static string FormatGlyph(int codePoint) => $"\\u{{{codePoint:X}}}";
}
